repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.2
    hooks:
    -   id: check-ast
    -   id: flake8
    -   id: check-case-conflict
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: docs/generated/
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
        exclude: /template/
    -   id: debug-statements
    -   id: name-tests-test
        args: [--django]
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: ^docs/source/conf.py$
    -   id: check-ast
    -   id: fix-encoding-pragma
        args: [--remove]
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        args: [
            '--remove-import', 'from __future__ import absolute_import',
            '--remove-import', 'from __future__ import division',
            '--remove-import', 'from __future__ import print_function',
            '--remove-import', 'from __future__ import unicode_literals',
        ]
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    sha: v0.6.4
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: local
    hooks:
    -   id: no-catchall-except
        name: Prevent catchall except
        entry: except:$
        language: pygrep
        files: \.py$
    -   id: no-dorp
        name: Prevent misspelling of drop
        entry: dorp
        language: pygrep
        files: \.(py|pyi|rst|md)$
    -   id: validatedoc
        name: Validate docs
        entry: ./validatedoc/validatedoc.py
        language: script
        types: [python]
-   repo: git://github.com/matthewbentley/pre-commit-mirrors-pep257
    sha: 'acc6d81940b8d38563929e7fde70696cea42da30'
    hooks:
    -   id: pydocstyle
